### ISSUE TITLE
New logo / icon

### ISSUE THREAD

**Issue by mansya** [schollz/find3-android-scanner#11]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by schollz** [comment]
@mansya I would love that, it would be greatly appreciated!

**Comment by mansya** [comment]
i have design logo for this project. what dou you think ? do you like it ?
![find3 android scanner](https://user-images.githubusercontent.com/33461607/41717873-55faa7be-7585-11e8-9ce6-a13d9c65a066.png)

**Comment by mansya** [comment]
hi sir. How ? can I continue to make pull requests about this logo? or let me know if there is something you want to change
