### ISSUE TITLE
Request to include find3 on F-Droid

### ISSUE THREAD

**Issue by renatocan** [schollz/find3-android-scanner#12]
Hi,

I noticed Find3 isn't available on F-Droid repo yet.  I'll open a request to include it, ok?

Thanks,

Renato.

**Comment by schollz** [comment]
Great thanks

**Comment by lightonflux** [comment]
The app is now available in F-Droid.

**Comment by lightonflux** [comment]
https://f-droid.org/en/packages/com.internalpositioning.find3.find3app/
