### ISSUE TITLE
No Data Found in FIND3 default server (cloud.internalpositioning.com)

### ISSUE THREAD

**Issue by rajesh-iosdev** [schollz/find3-android-scanner#8]
**Expected Behavior**
I'm assuming that i can see all my locations in the FIND3 dashboard, similar to the FIND

**Actual Behavior**
After opening the FIND3 dashboard i dont see any location which i have learned previously. All i can see is the loader (Progress Icon) keeps loading and no value after waiting so long 

**Steps to Reproduce the Problem**
1. Download FIND3 android app
2. Fill the text field for Family, Device and Location and then tap on 'Tracking' button
3. Now tap on 'Start Scan' and wait for sometime
4. After some time, now tap on the above link which points to "Cloud.InternalPositioning.com"

Specifications
Version: FIND3 current version in the play store
Platform: Android
Subsystem: N/A

**Comment by schollz** [comment]
What's your group name

**Comment by rajesh-iosdev** [comment]
I'm assuming that it's the family name . If so, then it's  vdsi-rmz-7-floor

**Comment by schollz** [comment]
https://cloud.internalpositioning.com/view/dashboard/vdsi-rmz-7-floor says does not exist

**Comment by rajesh-iosdev** [comment]
More over .. I just created a new family and posted few data and tried to
reach but it doesn't so anything.. please see below screenshots.. let me
know if I'm missing something..
But FIND 0.5 is working fine for me...

**Comment by schollz** [comment]
I don't understand, without a family I can't say anything, and there are no screenshots.

**Comment by cuberinooo** [comment]
I have a similar problem. Downloading the App and typing family name + device name + location and do learning nothing happens.

btw. family name is labhs; device name is tablet
