### ISSUE TITLE
Unable to track using FIND3 android app

### ISSUE THREAD

**Issue by rajesh-iosdev** [schollz/find3-android-scanner#9]
Expected Behavior
FIND3 android app should be able to track and get my location.

Actual Behavior
After learning for about a minute, when I tap on start scan in tracking mode, I don't see my location after waiting for almost a minute.
Family name miraclemonster

Steps to Reproduce the Problem

Download FIND3 android app
Fill the text field for Family, Device and Location and then tap on 'Tracking' button
Now tap on 'Start Scan' and wait for sometime
Change to tracking mode and tap on start scan
It says running but no location gets printed..

Version: FIND3 current version in the play store
Platform: Android
Subsystem: N/A

https://drive.google.com/folderview?id=1Gc1ytizx8hq3Dz_WThbE0-AJNfqYhffn

**Comment by schollz** [comment]
I don't think you are connecting to the server. I don't see any data with that database either - which means no fingerprints are arriving at the server.
